In [1]:
print("hello world")


hello world


In [4]:
%pip install librosa==0.9.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.3/214.3 kB 9.2 MB/s eta 0:00:00
  Obtaining dependency information for audioread>=2.1.9 from https://files.pythonhosted.org/packages/57/8d/30aa32745af16af0a9a650115fbe81bde7c610ed5c21b381fca0196f3a7f/audioread-3.0.1-py3-none-any.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 3.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 3.7 MB/s eta 0:00:0000:0100:01
  Obtaining dependency information for pooch>=1.0 from https://files.pythonhosted.org/packages/1a/a5/5174dac3957ac412e80a00f30b6507031fcab7000afc9ea0ac413bddcff2/pooch-1.8.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 13.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip install matplotlib==3.3.4

Note: you may need to restart the kernel to use updated packages.


In [3]:
import os
import glob
#import librosa
#import pandas as pd
import json
import numpy as np
#import matplotlib.pyplot as plt
from keras.models import load_model
import tensorflow as tf
from tensorflow.keras.models import load_model
import IPython.display as ipd
from IPython.display import Audio



2023-12-27 09:05:57.366872: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-27 09:05:57.962761: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9360] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-27 09:05:57.963288: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-27 09:05:57.966161: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1537] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-27 09:05:58.185466: I tensorflow/core/platform/cpu_feature_g

In [13]:
RAVD = "data_sources/RAVDESS/audio_speech_actors_01-24/"
audio_path = RAVD + 'Actor_18/03-01-05-01-01-01-18.wav' # Gender - Female; Emotion - angry
ipd.Audio(audio_path)

In [4]:

# Load the trained model
model_path = "./data_sources/saved_models/model03.h5"
loaded_model = load_model(model_path)

2023-12-27 09:06:41.601219: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-27 09:06:41.685333: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-27 09:06:41.685361: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-27 09:06:41.688857: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-27 09:06:41.688898: I tensorflow/compile

In [5]:
'''def get_feat(path):
    data, sample_rate = librosa.load(path, duration=2.5, offset=0.5)
    mfccs = np.mean(librosa.feature.mfcc(y=data, sr=sample_rate).T, axis=0)
    # normal data
    res1 = mfccs
    result = np.array(res1)

    # result = np.vstack((result, res1))
    return result'''


In [14]:
#import numpy as np
data, sample_rate = librosa.load(audio_path, duration=2.5, offset=0.5)
mfccs = np.mean(librosa.feature.mfcc(y=data, sr=sample_rate).T, axis=0)
# normal data
res1 = mfccs
result = np.array(res1)

In [15]:
result

array([-462.33716   ,   73.48705   ,  -36.58055   ,    1.8796564 ,
        -15.968939  ,  -15.391061  ,   -9.044473  ,  -20.293709  ,
        -24.46661   ,    0.96487707,   -8.772957  ,   -7.2059965 ,
         -7.6809387 ,   -7.409683  ,   -7.591559  ,  -11.131728  ,
        -12.204274  ,   -3.2369578 ,   -9.203673  ,   -3.0469944 ],
      dtype=float32)

In [16]:
result = result.reshape(1, -1)

In [17]:
twodim= np.expand_dims(result, axis=2)

In [18]:
twodim

array([[[-462.33716   ],
        [  73.48705   ],
        [ -36.58055   ],
        [   1.8796564 ],
        [ -15.968939  ],
        [ -15.391061  ],
        [  -9.044473  ],
        [ -20.293709  ],
        [ -24.46661   ],
        [   0.96487707],
        [  -8.772957  ],
        [  -7.2059965 ],
        [  -7.6809387 ],
        [  -7.409683  ],
        [  -7.591559  ],
        [ -11.131728  ],
        [ -12.204274  ],
        [  -3.2369578 ],
        [  -9.203673  ],
        [  -3.0469944 ]]], dtype=float32)

In [19]:
livepreds = loaded_model.predict(twodim, 
                         batch_size=32, 
                         verbose=1)

2023-11-05 07:25:48.882014: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:432] Loaded cuDNN version 8905


1/1 [==============================] - 1s 1s/step


2023-11-05 07:25:49.620113: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:625] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


In [20]:
livepreds

array([[6.5486995e-04, 6.2136323e-04, 6.5933511e-04, 9.0933982e-03,
        5.5069369e-03, 2.1655754e-04, 9.7097093e-01, 1.4043022e-04,
        5.5197292e-05, 4.0991104e-05, 3.2756394e-03, 2.9780241e-03,
        4.3824166e-03, 2.1765572e-04, 5.0955254e-04, 6.7670434e-04]],
      dtype=float32)

In [21]:
livepreds.shape

(1, 16)

In [22]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

'''Y = ['male_calm',
'female_calm',
'female_neutral',
'male_neutral',
'male_sad',           
'male_fear',           
'male_happy',      
'male_disgust',       
'male_angry',          
'male_surprise',    
'female_surprise',    
'female_disgust',    
'female_fear',        
'female_sad',          
'female_happy',       
'female_angry']

In [25]:
labels = {'labels': ['female_neutral', 'male_neutral', 'male_sad',
                   'male_fear', 'male_happy', 'male_disgust', 'male_angry', 'male_surprise',
                   'female_surprise', 'female_disgust', 'female_fear', 'female_sad',
                   'female_happy', 'female_angry', 'male_calm', 'female_calm']}

df = pd.DataFrame(labels)
Emotions = df
Emotions

labels
0    female_neutral
1      male_neutral
2          male_sad
3         male_fear
4        male_happy
5      male_disgust
6        male_angry
7     male_surprise
8   female_surprise
9    female_disgust
10      female_fear
11       female_sad
12     female_happy
13     female_angry
14        male_calm
15      female_calm

In [26]:
Y = Emotions['labels'].values
Y

array(['female_neutral', 'male_neutral', 'male_sad', 'male_fear',
       'male_happy', 'male_disgust', 'male_angry', 'male_surprise',
       'female_surprise', 'female_disgust', 'female_fear', 'female_sad',
       'female_happy', 'female_angry', 'male_calm', 'female_calm'],
      dtype=object)

In [27]:
Y = encoder.fit_transform(np.array(Y).reshape(-1,1)).toarray()
Y

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [28]:

livepredictions = (encoder.inverse_transform(livepreds))
livepredictions

array([['female_sad']], dtype=object)